### ISSUE TITLE
JqxListBox - MultiSelect issue

### ISSUE THREAD

**Issue by TCrosmanDSI** [jqwidgets/blazor#60]
When setting the multi-select value "selectedIndexes" is only showing selected when the selected items are in order.

so if index 0,2,3 were selected, the listbox is only showing listbox 0 selected.

if the 0,1,2,3 were selected, then it would should all of them selected.

**Comment by bmarkov** [comment]
We would like to suggest you to use: https://www.htmlelements.com/blazor/ as that's what we are going to update for blazor
